#!/usr/bin/env bash
# I am alive
declare -a instruction=(
[0]="start"
[1]="stop"
[2]="restart"
)
id=$(pgrep "manage_my_process" -f)
for (( i=0 ; i<=4 ; i++ ));
do
if [ i==0 ]; then
manage_my_process
echo $$ > /var/run/my_process.pid
echo "manage_my_process started"
echo "manage_my_process stopped"
echo "manage_my_process restarted"
elif [ i==1 ]; then
manage_my_process
rm /var/run/my_process.pid
echo "manage_my_process stopped"
elif [ i==2 ]; then
service "$id" stop
rm /var/run/my_process.pid
manage_my_process
echo $$ > /var/run/my_process.pid
echo "manage_my_process restarted"
else
echo "Usage: manage_my_process {start|stop|restart}"
fi
done
