#!/usr/bin/env bash                                                                                                             
# displaying processes                                                                                                          
# shellcheck disable=SC2009
ps -l bash
