#!/usr/bin/env bash                                                            
# Best school 10 times using while loop                                        
# shellcheck disable=SC2009
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)
if [ -n $id ]
then
	kill -15 "$id"
fi
