#!/usr/bin/env bash                                                             # displaying ubdefinitely                                                      
while true; do
echo "To infinity and beyond"
kill -15
done    					
