#!/usr/bin/env bash                                                                                                             
# displaying ubdefinitely                                                                                                    
# shellcheck disable=SC2009
while true; do 
echo "To infinity and beyond"
kill -1
done    					
