#!/usr/bin/env bash                                                             # displaying ubdefinitely                                                      
trap 'echo"I am invincible!!!"' 15
while true; do 
echo "To infinity and beyond"
sleep 2
done    					
